# Generated by Django 4.2.30 on 2026-09-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swgfApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo_prioridade', models.CharField(blank=True, help_text='Ex: idoso, gestante, PCD, normal', max_length=50, null=True, verbose_name='Tipo de prioridade')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número da mesa')),
                ('status', models.CharField(default='disponivel', help_text='Ex: disponivel, ocupada, inativa', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('status', models.CharField(default='aguardando', help_text='Ex: aguardando, chamada, atendida', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Senha',
                'verbose_name_plural': 'Senhas',
            },
        ),
    ]
