# Generated by Django 4.2.30 on 2026-09-27 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swgfApp', '0002_cliente_mesa_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Início da sessão')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim da sessão')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swgfApp.mesa', verbose_name='Mesa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Mesa',
                'verbose_name_plural': 'Sessões de Mesa',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de emissão')),
                ('hora_atendimento', models.TimeField(blank=True, null=True, verbose_name='Hora de atendimento')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swgfApp.cliente', verbose_name='Cliente')),
                ('senha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swgfApp.senha', verbose_name='Senha')),
                ('sessao_mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swgfApp.sessaomesa', verbose_name='Sessão de Mesa')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
